name: Build mod zip

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-zip:
    strategy:
      matrix:
        branch: [main, pugs_ver]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      
      - name: Create folder
        run: |
          mkdir -p Dinorush.LTSRebalance_ && cp -R mods/ icon.png LICENSE manifest.json README.md Dinorush.LTSRebalance_/

      - name: Prepare image tag
        run: |
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      - name: Prepare zip file name
        run: |
          if [[ "${{ matrix.branch }}" == "pugs_ver" ]]; then
            echo ZIP_SUFFIX="_pugs_ver" >> $GITHUB_ENV
          else
            echo ZIP_SUFFIX="" >> $GITHUB_ENV
          fi

      - uses: vimtor/action-zip@v1
        with:
          files: ./Dinorush.LTSRebalance_
          dest: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}${{ env.ZIP_SUFFIX }}.zip
            
      - name: Attach the mod to the release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}${{ env.ZIP_SUFFIX }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
