name: Docker Image CI
on:
  release:
    types: [published]
jobs:
  upload-zip:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Create folder
        run: |
          mkdir -p Dinorush.LTSRebalance && cp -R mod.json mod/ keyvalues/ Dinorush.LTSRebalance/

      - name: Prepare image tag
        run: |
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      - uses: papeloto/action-zip@v1
        with:
          files: ./Dinorush.LTSRebalance
          dest: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip

