name: Build mod zip

on:
  push:
    tags:
      - 'v*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get clean version
        run: |
          echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
      - name: Check that version matches
        run: |
          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
            echo "::debug::${{env.cleanVersion}}"
            echo "::debug::$(cat $(find ./ -name mod.json ))"
            echo "::error::Version in mod.json does not match tag version"
            exit 1
          fi
  publish:
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      
      - name: Create Folders
        run: |
          mkdir -p Dinorush.LTSRebalance && cp -R mods/ icon.png LICENSE manifest.json README.md Dinorush.LTSRebalance/
          git apply pugs_ver.patch
          mkdir -p Dinorush.LTSRebalance_pugs_ver && cp -R mods/ icon.png LICENSE manifest.json README.md Dinorush.LTSRebalance_pugs_ver/

      - name: Prepare image tag
        run: |
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      - uses: vimtor/action-zip@v1
        name: zip rebalanced
        with:
          files: ./Dinorush.LTSRebalance
          dest: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip

      - uses: vimtor/action-zip@v1
        name: zip pugs version rebalanced
        with:
          files: ./Dinorush.LTSRebalance_pugs_ver
          dest: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}_pugs_ver.zip
            
      - name: Attach the mod to the release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach the mod to the release for pugs version
        uses: softprops/action-gh-release@v1
        with:
          files: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}_pugs_ver.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload to Thunderstore
        uses: GreenTF/upload-thunderstore-package@v3.1
        with:
          community: northstar
          namespace: ${{ github.repository_owner }}
          name: LTS_Rebalance
          version: ${{ github.ref_name }}
          description: Rebalances titans for better meta diversity, especially in LTS.
          token: ${{ secrets.TS_KEY }}
          file: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip
          categories: Mods Server-side Client-side