name: Build mod zip

on:
  push:
    tags:
    - 'v*' 

jobs:
  upload-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Create folder
        run: |
          mkdir -p Dinorush.LTSRebalance && cp -R mod.json mod/ keyvalues/ Dinorush.LTSRebalance/

      - name: Prepare image tag
        run: |
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      - uses: vimtor/action-zip@v1
        with:
          files: ./Dinorush.LTSRebalance
          dest: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip
            
      - name: Attach the mod to the release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
