name: Build mod zip

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      
      - name: Create Folders
        run: |
          mkdir -p Dinorush.LTSRebalance && cp -R mods/ icon.png LICENSE manifest.json README.md Dinorush.LTSRebalance/
          git apply pugs_ver.patch
          mkdir -p Dinorush.LTSRebalance_pugs_ver && cp -R mods/ icon.png LICENSE manifest.json README.md Dinorush.LTSRebalance_pugs_ver/

      - name: Prepare image tag
        run: |
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      - uses: vimtor/action-zip@v1
        name: zip rebalanced
        with:
          files: ./Dinorush.LTSRebalance
          dest: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip

      - uses: vimtor/action-zip@v1
        name: zip pugs version rebalanced
        with:
          files: ./Dinorush.LTSRebalance_pugs_ver
          dest: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}_pugs_ver.zip
            
      - name: Attach the mod to the release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach the mod to the release for pugs version
        uses: softprops/action-gh-release@v1
        with:
          files: ./Dinorush.LTSRebalance_${{ env.IMAGE_TAG }}_pugs_ver.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}